import type { Metadata } from "next";
import { Moirai_One, Modak, Roboto } from "next/font/google";
import "../styles/global.scss";

export const moirai = Moirai_One({
  subsets: ['latin'],
  weight: ["400"],
  variable: '--font-moirai',
  display: 'swap'
});

export const modak = Modak({
  subsets: ['latin'],
  weight: ["400"],
  variable: '--font-modak',
  display: 'swap'
});

export const roboto = Roboto({
  subsets: ['latin'],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: '--font-roboto',
  display: 'swap'
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR"
      className={`${moirai.variable} ${modak.variable} ${roboto.variable}`}>
      <body >
        {children}
      </body>
    </html>
  );
}
